name: Azure Petclinic CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
   
jobs:
  criarInfra:
    runs-on: ubuntu-latest
    steps:
      - name: Login no Azure
        uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true

      - name: Criar grupo de recursos
        run: |
     #     az group create --location eastus --name FiapResourceGroup

      - name: Criar plano de serviço App Service (Linux)
        run: |
      #    az appservice plan create -g FiapResourceGroup -n PlanoServicoSpring --is-linux --sku F1

      - name: Criar Web App com Java 17
        run: |
          az webapp create -g FiapResourceGroup -p PlanoServicoSpring -n pert-clinic-pf1167 --runtime "JAVA:17-java17"

  buildApp:
    runs-on: ubuntu-latest
    needs: criarInfra
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build PetClinic
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: petclinic
          path: target/*.jar

  deployApp:
    runs-on: ubuntu-latest
    needs: buildApp
    steps:
      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: petclinic

      - name: Deploy Petclinic
        uses: azure/webapps-deploy@v3
        with:
          app-name: pert-clinic-pf1167
          package: "*.jar"
